openapi: 3.0.1
info:
  title: Example API
  description: Random API.
  termsOfService: 'https://swagger.io/tools/swaggerhub/'
  contact:
    email: pablo.gonzalez.granados@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 2.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'http://localhost:8082'
    description: local enviroment
tags:
  - name: examples
    description: Access to examples api
security:
  - bearerAuth: []
paths:
  /hello/{name}/world:
    get:
      tags:
        - helloWorld
      summary: hello world example
      description: just a clasic helloWorld example
      operationId: helloByName
      parameters:
        - name: name
          in: path
          description: Pablo, David, Laura...etc
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successfull helloWorld
          content:
            text/plain:
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
